column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
<<<<<<< HEAD
no_call_parentheses = true
=======
call_parentheses = "None"
>>>>>>> 85d95dfdddba7077257a5fa3eb6dd57caf12579f
